// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedisApplication.Models;

#nullable disable

namespace RedisApplication.Migrations
{
    [DbContext(typeof(RedisDbContext))]
    partial class RedisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedisApplication.Models.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CauseOfLoss")
                        .HasColumnType("int");

                    b.Property<string>("ContactAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeclarationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ExcessAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GarageType")
                        .HasColumnType("int");

                    b.Property<int?>("LossReporter")
                        .HasColumnType("int");

                    b.Property<int?>("MotorInsurerPaidClaimStatus")
                        .HasColumnType("int");

                    b.Property<int?>("PayeeType")
                        .HasColumnType("int");

                    b.Property<int?>("PreferredChannel")
                        .HasColumnType("int");

                    b.Property<decimal?>("RepairingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TypeOfLoss")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Claims", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
